### ISSUE TITLE
Push Exception - branches with same name

### ISSUE THREAD

**Issue by Klap-in** [dokufreaks/dokuwiki-translation#93]
push exception is not well handled by translation tool.
Push exception occurs because on GitHub there exists already a previous branch with same name. 

---

`lang_update_66` has **not** appeared at Github. But there is already a 3 year old pull request with same name. (see https://github.com/dokuwiki-translate/dokuwiki/tree/lang_update_66)
`/tmp/66` is not available at server anymore.

```
[2016-08-25 07:55:01] app.DEBUG: updating plugin howhard [] []
[2016-08-25 07:55:07] app.DEBUG: updating plugin charpicker [] []
[2016-08-25 07:55:10] app.DEBUG: updating plugin sqlite [] []
[2016-08-25 07:55:13] app.DEBUG: updating plugin multiorphan [] []
[2016-08-25 07:55:16] app.DEBUG: updating plugin purplenumbers [] []
[2016-08-25 07:55:19] app.DEBUG: updating plugin templatepagename [] []
[2016-08-25 07:55:31] app.ERROR: error during repository update (org\dokuwiki\translatorBundle\Services\Git\GitPushException: Failed to push to github/lang_update_66
Path: /var/www/translate/data/plugin/indexmenu/tmp/66/
Command: /usr/bin/git 'push' 'github' 'lang_update_66'
Return : 1
STDOUT : 
STDERR : To git@github.com:dokuwiki-translate/indexmenu.git
 ! [rejected]        lang_update_66 -> lang_update_66 (fetch first)
error: failed to push some refs to 'git@github.com:dokuwiki-translate/indexmenu.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
) [] []
[2016-08-25 07:55:31] app.DEBUG: #0 /var/www/translate/htdocs/src/org/dokuwiki/translatorBundle/Services/Repository/Behavior/GitHubBehavior.php(37): org\dokuwiki\translatorBundle\Services\Git\GitRepository->push('github', 'lang_update_66')
#1 /var/www/translate/htdocs/src/org/dokuwiki/translatorBundle/Services/Repository/Repository.php(327): org\dokuwiki\translatorBundle\Services\Repository\Behavior\GitHubBehavior->sendChange(Object(org\dokuwiki\translatorBundle\Services\Git\GitRepository), Object(org\dokuwiki\translatorBundle\Entity\TranslationUpdateEntity), Object(org\dokuwiki\translatorBundle\Services\Git\GitRepository))
#2 /var/www/translate/htdocs/src/org/dokuwiki/translatorBundle/Services/Repository/Repository.php(307): org\dokuwiki\translatorBundle\Services\Repository\Repository->createAndSendPatchWithException(Object(org\dokuwiki\translatorBundle\Entity\TranslationUpdateEntity), '/var/www/transl...')
#3 /var/www/translate/htdocs/src/org/dokuwiki/translatorBundle/Command/UpdateCommand.php(74): org\dokuwiki\translatorBundle\Services\Repository\Repository->createAndSendPatch(Object(org\dokuwiki\translatorBundle\Entity\TranslationUpdateEntity))
#4 /var/www/translate/htdocs/src/org/dokuwiki/translatorBundle/Command/UpdateCommand.php(37): org\dokuwiki\translatorBundle\Command\UpdateCommand->processPendingTranslations()
#5 /var/www/translate/htdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(238): org\dokuwiki\translatorBundle\Command\UpdateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/translate/htdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(199): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/translate/htdocs/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(78): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/translate/htdocs/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(105): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/translate/htdocs/app/console(22): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#10 {main} [] []
```

**Comment by Klap-in** [comment]
- in `<datafolder>/<type>/<name>/<id>.update` are still the not submitted language updates
- other failed pushes have also still stale branches with the same name in the repository

solutions:
- remove automatically old and merged branches (how to detect?)
- smart numbering/higher start number to prevent overlapping numbers

NOTE: maybe useful to check for not submitted language updates, however, some could be already changed..

**Comment by Klap-in** [comment]
Searching for a nice git approach to remove the  _merged_ branches from the remote repository is not so convenient. e.g. [stackoverflow question](http://stackoverflow.com/questions/6127328/how-can-i-delete-all-git-branches-which-have-been-merged)

Who has experience with this kind of maintenance of a remote git repository?
